# Generated by Django 3.1.2 on 2020-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMSAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
