# Generated by Django 3.1.2 on 2020-12-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMSAPI', '0003_auto_20201207_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='COMSAPI.client'),
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.FileField(upload_to=''),
        ),
    ]
