# Generated by Django 3.1.2 on 2020-12-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMSAPI', '0004_auto_20201209_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='filename',
            new_name='file',
        ),
    ]
