# Generated by Django 3.1.2 on 2020-12-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMSAPI', '0005_auto_20201209_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='COMSAPI.module'),
        ),
    ]
