# Generated by Django 3.1.2 on 2020-12-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMSAPI', '0006_task_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='file',
            field=models.FileField(upload_to='uploads/modules/'),
        ),
    ]
