# Generated by Django 3.1.2 on 2020-12-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMSAPI', '0007_auto_20201210_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='COMSAPI.task')),
            ],
        ),
    ]
